name: .NET + NuGet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Publish-prerelease:
    if: contains(github.head_ref, 'main') 
    
    pack-push:
      env:
        CAMINHO_PROJETO: ./Groffe.Distancias/Groffe.Distancias.csproj
      
      runs-on: ubuntu-latest

      steps:
      - name: checkout        
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Semantic versioning
        id: versioning
        uses: PaulHatch/semantic-version@v4.0.2
        with:
          branch: main
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          format: "v${major}.${minor}.${patch}-prerelease${increment}"

      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.101
        
      - name: Geração do package
        run: dotnet pack ${{ env.CAMINHO_PROJETO }} -c Release -o out
      
      - name: Push no NuGet
        run: |
          cd out 
          dotnet nuget push '${{ env.CAMINHO_PROJETO }}/*.npkg' --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_SERVER }} --skip-duplicate
